services:
  _defaults:
    public: true

  ContaoCommunityAlliance\Merger2\EventListener\Hook\LoadFunctionExplanationsListener:
    arguments:
      - '@cca.merger2.function_collection'
      - '@twig'
