defaults:
  public: true

services:
  ContaoCommunityAlliance\Merger2\EventListener\Hook\LoadFunctionExplanationsListener:
    arguments:
      - '@cca.merger2.function_collection'
      - '@templating'
