services:
  cca.merger2.constraint_parser:
    class: ContaoCommunityAlliance\Merger2\Constraint\Parser\Parser
    arguments:
      - "@cca.merger2.function_collection"

  cca.merger2.function_collection:
    class: ContaoCommunityAlliance\Merger2\Functions\FunctionCollectionCollection
    arguments:
      - []

  cca.merger2.standard_functions:
    class: ContaoCommunityAlliance\Merger2\Functions\StandardFunctionsCollection
    arguments:
      - "@mobile_detect.mobile_detector"
      - "@doctrine.dbal.connection"
    tags:
      - { name: cca.merger2.function_collection }
